// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb/src/Breadcrumb.vue')['default']
    ComponentMap: typeof import('./components/SearchForm/componentMap.tsx')['default']
    Dropdown: typeof import('./components/Dropdown/index.vue')['default']
    Filter: typeof import('./components/Filter/index.vue')['default']
    Icon: typeof import('./components/Icon/index.vue')['default']
    Iconfont: typeof import('./components/Iconfont/index.tsx')['default']
    SearchForm: typeof import('./components/SearchForm/index.vue')['default']
    Table: typeof import('./components/Table/index.vue')['default']
  }
}

export { }
